#!/usr/bin/env php
<?php

use think\App;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

/** @var App $app */
$app = require_once __DIR__.'/bootstrap/app.php';

// 应用初始化
$app->console->run();
